language: php
php:
  - 7.0
  - 7.1
install:
  # Composer
  - composer self-update
  - composer create-project bluzphp/skeleton --stability=dev
  - cd skeleton
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
  # Require current module
  - composer require bluzphp/module-categories:dev-master
  # Migrations
  - php vendor/bin/bluzman db:migrate
  - php vendor/bin/bluzman db:seed:run
script:
  # Code style
  - php vendor/bin/phpcs ./application --standard=PSR1,PSR2 --encoding=utf-8 --ignore=./application/_loader.php
  # WebServer run
  #- nohup bash -c "php -S 127.0.0.1:8000 -t ./public/ ./public/routing.php 2>&1 &" && sleep 1; cat nohup.out
  - php vendor/bin/bluzman server:start --host 127.0.0.1 -b
  # CodeCeption
  - php vendor/bin/bluzman test module-categories
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
branches:
  only:
  - master
  - develop
