<?php
/** @var Application\Categories\Row $category */
$rootId = $category->rootId ?: $category->id;
$children = $category->getChildren();
?>

<div class="d-flex justify-content-between">
  <h5 class="mt-2"><?= esc($category->name) ?></h5>
  <div>
    <a href="<?= $this->url('categories', 'crud', ['parentId' => $category->id, 'rootId' => $rootId]) ?>"
       class="btn btn-success dialog create" data-ajax-method="get">
        <i class="fa fa-plus"></i>
    </a>
    <a href="<?= $this->url('categories', 'crud', ['id' => $category->id, 'rootId' => $rootId]) ?>"
       class="btn btn-primary dialog edit" data-ajax-method="get">
        <i class="fa fa-pencil"></i>
    </a>
    <?php if ($children) : ?>
    <span class="btn btn-danger disabled"><i class="fa fa-trash-o"></i></span>
    <?php else: ?>
    <a href="<?= $this->url('categories', 'crud', ['id' => $category->id]) ?>"
       class="btn btn-danger ajax confirm delete<?=($rootId === $category->id)?'-root':''?>" data-ajax-method="delete">
        <i class="fa fa-trash-o"></i>
    </a>
    <?php endif; ?>
  </div>
</div>

<?php if ($children) : ?>
    <ol class="list-group mt-2">
        <?php foreach ($children as $child) : ?>
        <li class="list-group-item">
            <?= $this->partial('partial/tree.phtml', ['category' => $child]) ?>
        </li>
        <?php endforeach;?>
    </ol>
<?php endif; ?>