<?php
namespace Application\Categories;

$uid = uniqid('form_', false);

if ($rootId) {
    // get tree of category
    // required array for view
    $tree = array(Table::getInstance()->buildTree($rootId));
} else {
    // get root categories
    $tree = Table::getInstance()->getRootCategories();
    $rootRow = new Row();
    $rootRow->name = '---';
    array_unshift($tree, $rootRow);
}

$parentId = $parentId ?: $row->parentId;
$rootId = $rootId ?: $row->rootId;
?>
<form id="<?= $uid ?>" action="<?= $this->url('categories', 'crud') ?>"
      class="form-horizontal ajax <?= $parentId ? 'add-child' : 'category-form' ?> <?= $row->id ? 'category-edit' : '' ?>"
      method="<?= $method ?>">
  <input type="hidden" name="id" value="<?= $row->id ?>"/>
  <input type="hidden" name="_method" value="<?= $method ?>"/>
  <input type="hidden" name="rootId" value="<?= $rootId ?>"/>
  <div class="modal-header">
    <h4 class="modal-title"><?= __('Category') ?></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="<?=__('Close')?>">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
      <?php if ($parentId && $rootId) : ?>
        <div class="form-group row">
          <label class="control-label col-lg-2" for="name"><?= __('Parent') ?></label>
          <div class="col-lg-10">
            <select class="form-control" name="parentId">
                <?php
                foreach ($tree as $category):
                    echo $this->partial(
                        'partial/option.phtml',
                        ['category' => $category, 'level' => 0, 'selected' => $parentId]
                    );
                endforeach;
                ?>
            </select>
          </div>
        </div>
      <?php endif; ?>
    <div class="form-group row">
      <label class="control-label col-lg-2" for="name"><?= __('Name') ?></label>
      <div class="col-lg-10">
        <input type="text" class="form-control" id="name" name="name" value="<?= esc($row->name) ?>"
               maxlength="255" required/>
      </div>
    </div>
    <div class="form-group row">
      <label class="control-label col-lg-2" for="alias"><?= __('Alias') ?></label>

      <div class="col-lg-10">
        <input type="text" class="form-control" id="alias" name="alias" value="<?= esc($row->alias) ?>"
               maxlength="255" required/>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
    <a href="#" class="btn btn-default" data-dismiss="modal"><?= __('Close') ?></a>
  </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>