<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<script>
  // use data-spy="grid" for use AJAX for reload grid
  require(['bluz.categories']);
</script>
<nav class="navbar navbar-light bg-light">
  <form action="" class="form-inline select-tree" style="width: 100%">
    <div class="input-group" style="width: 100%">
      <label for="root" class="input-group-addon"><?= __('Module') ?></label>
      <select id="root" class="form-control">
          <?php foreach ($rootTree as $tree) : ?>
            <option value="<?php echo $tree->id ?>"><?php echo $tree->name ?></option>
          <?php endforeach; ?>
      </select>
      <span class="input-group-btn">
      <a href="<?= $this->url('categories', 'crud') ?>"
         class="btn btn-secondary form-group dialog create-root"
         data-ajax-method="get"><?= __('Create') ?></a>
      </span>
    </div>
  </form>
</nav>
<hr/>
<div class="tree-container">
  <div class="tree-wrapper list-group">
    <?php if (isset($category)) : ?>
    <div class="list-group-item d-flex flex-wrap flex-column">
      <?= $this->partial('partial/tree.phtml', ['category' => $category]) ?>
    </div>
    <?php else: ?>
    <h3>There are no categories</h3>
    <?php endif; ?>
  </div>
</div>
