<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<script>
  // use data-spy="grid" for use AJAX for reload grid
  require(['bluz.categories']);
</script>
<nav class="navbar navbar-light bg-light justify-content-between">
  <div class="col-8">
    <form action="" class="select-tree">
      <div class="input-group">
        <div class="input-group-prepend">
          <label for="root" class="input-group-text"><?= __('Module') ?></label>
        </div>
        <select id="root" class="form-control">
          <?php foreach ($rootTree as $tree) : ?>
            <option value="<?php echo $tree->id ?>"><?php echo $tree->name ?></option>
          <?php endforeach; ?>
        </select>
      </div>
    </form>
  </div>
  <div class="col-4">
    <a href="<?= $this->url('categories', 'crud') ?>"
       class="btn btn-secondary create-root"
       data-ajax-dialog data-ajax-method="get"><?= __('Create') ?></a>
  </div>
</nav>
<hr/>
<div class="tree-container">
  <div class="tree-wrapper list-group">
    <?php if (isset($category)) : ?>
    <div class="list-group-item d-flex flex-wrap flex-column">
      <?= $this->partial('partial/tree.phtml', ['category' => $category]) ?>
    </div>
    <?php else: ?>
    <p>There are no categories</p>
    <?php endif; ?>
  </div>
</div>
